spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:restapidb
    username: sa
    password: toure
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true